services:
  mysql:
    container_name: temporal-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: mysql:9.3.0
    networks:
      - temporal-network
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
  temporal:
    container_name: temporal
    depends_on:
      - mysql
    environment:
      - DB=mysql8
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
    image: temporalio/auto-setup:1.27.2
    networks:
      - temporal-network
    ports:
      - 7233:7233
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
