# This file is adapted from the official Temporal Docker Compose setup for MySQL.
# Source: https://github.com/temporalio/docker-compose/blob/v1.27.2/docker-compose-mysql.yml
# Originally licensed under the MIT License:
# https://opensource.org/licenses/MIT
#
# The modifications in this file are licensed under the Apache License 2.0.

services:
  mysql:
    container_name: temporal-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # https://hub.docker.com/_/mysql
    image: mysql:9.3.0
    networks:
      - temporal-network
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
  temporal:
    container_name: temporal
    depends_on:
      - mysql
    environment:
      - DB=mysql8
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    # https://hub.docker.com/r/temporalio/auto-setup/tags
    image: temporalio/auto-setup:1.27.2
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    # https://hub.docker.com/r/temporalio/admin-tools/tags
    image: temporalio/admin-tools:1.27.2-tctl-1.18.2-cli-1.3.0
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    # https://hub.docker.com/r/temporalio/ui/tags
    image: temporalio/ui:v2.38.2
    networks:
      - temporal-network
    ports:
      - 8080:8080
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
